apiVersion: sampledb.beta/v1
kind: MongoDB
metadata:
  name: nginx
  namespace: default
spec:
  image: "nginx:latest"
  storage:
    class: gp2
    size: 20GiB
  secrets:
    user: test
    password: test123
    db: test-db
  service:
    type: loadbalancer
   